#title in header
title: "🐳 Ryan Lam"

#main info
#owner
index_title: "Hi There!"
# email:
info: ""
#description
desc: ""

#menu
menu:
  # Home: /
  Experience: /experience
  Links: /links

#index/main page max show posts (in number)
max_post: 4

# Colors use hex color without #
# Theme color
tcolor: 0FA0CE

# Define path to user css
#(could be also located outside of theme)
# Relative to source/ directory
usercss: css/user.css

# social profile at the footer/bottom
footer: true
# placename:
# placelink:
github: https://github.com/ryan-lam
linkedin: https://www.linkedin.com/in/ryanlam285/
# twitter:
# instagram:

# Misc
nanobar: /js/nanobar.min.js
# switch_light:
# switch_dark:

# favicon
favicon: /images/favicon.png
# # thumbnail
# thumbnail:

article:
  thumbnail: true

# DISQUS comments (sign up to Disqus to get disqus_shortname)
disqus_enabled: false
disqus_shortname:
